spring.application.role=Projekt_Zespolowy
server.port=8089

spring.datasource.url=jdbc:postgresql://ep-summer-flower-ag34knpm-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vNO0HdlM8PcJ

spring.datasource.driver-class-role=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=mJ8v7kQ2p1sZ9xA4rT6uW0yL3cD5fH8nVb2QeR7tYkM=
jwt.expiration=3600000
